version: "3"
services:
  butlerbot:
    image: 'butlerx/butlerbot:latest'
    restart: 'always'
    volumes:
      - ./bookclub:/usr/src/app/pluginCode/bookclub/config
      - ./countdown:/usr/src/app/pluginCode/countdown/config
    environment:
      SERVER: localhost
      PORT: 6697
      NICK: butlerbot
      USER: butlerx
      NODE_ENV: development
      TARGET: Nickserv
      MESSAGE: identify
